name: Tag Workflow
on:
  push:
    # 使用tags/*来监听所有的tag事件
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with current tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          #python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project with Nuitka-Action
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: true
          enable-plugins: pyqt6
          disable-console: true
          windows-icon-from-ico: app/resource/images/logo.ico

      - name: Compress files
        run:
          Compress-Archive -Path build/  -DestinationPath release/onemore_${{ steps.get_tag.outputs.tag }}.zip 
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false
        
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/onemore_${{ steps.get_tag.outputs.tag }}.zip
          asset_name: onemore_${{ steps.get_tag.outputs.tag }}.zip
          asset_content_type: application/zip

      # - name: upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows Build
      #     tagname: ${{ steps.get_tag.outputs.tag }}
      #     path: release/onemore_${{ tagname }}.zip 