name: Tag Workflow
on:
  push:
    # 使用tags/*来监听所有的tag事件
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with current tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          #python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project with Nuitka-Action
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: true
          enable-plugins: pyqt6
          disable-console: true
          windows-icon-from-ico: app/resource/images/logo.ico

      - name: Compress files
        run:
          Compress-Archive -Path build/  -DestinationPath release/onemore_${{ github.ref }}.zip 
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows Build
          path: release/onemore_${{ github.ref }}.zip
    
